### ISSUE TITLE
Improvement: Support nastran file MPC entries

### ISSUE THREAD

**Issue by kristsaet** [openfedem/fedem-gui#36]
As at least ANSYS is really happy to create meshes, using lots of MPC entities, it would be convenient that Fedem supported this way of creating a mesh.

**Comment by kristsaet** [comment]
Ok, I did not see that it already was an issue related to MPC..

**Comment by kmokstad** [comment]
Indeed, this was requested already in #7. It turns out we already support MPCs in the SESAM file reader (see the method [FFlSesamReader::readLinearDependencies()](https://github.com/openfedem/fedem-foundation/blob/main/src/FFlLib/FFlIOAdaptors/FFlSesamReader.C#L390)), where they are converted into equivalent `WAVMG` elements (which again are representation of RBE3-Nastran elements). Therefore, #7 can be fixed by doing a similar implementation for the Nastran reader.

@kristsaet if you have a sample Nastran file with MPC-entries for testing, we may have this available relatively soon. It can be attached to issue #7 or sent by email to kmo@openfedem.org
