### ISSUE TITLE
Cylindrical joint slave triad rotates out of the cylindrical axis

### ISSUE THREAD

**Issue by kristsaet** [openfedem/fedem-gui#50]
It is observed that the cylindrical joint will rotate out of the cylinder axis when the triad is attached to a part which will not restrain any rotations of the triad itself.

This is a bit unexpected, and should probably be checked out.

**Comment by kmokstad** [comment]
This is actually the expected behavior, and is also documented as such in the Theory Guide (see sections 6.3.1 and 6.3.2). It is stated there that the slave part is free to rotate about the local X- and Y-axes of the multi-master joint and also about the local Z-axis (the cylinder axis) of the Cylindric joint. The cylindric joint therefore only constrains the translational motion - not the rotations. If rotational constraints are needed, a second joint connecting the same two parts must be added.

Therefore, closing this issue as nothing to be fixed.
